[workspace]
members = [
  "./frontend",
  "./backend",
  "./data_types", 
  "./throttling-tests"
]
resolver = "2"

[profile.dev]
incremental = true

[profile.release]
opt-level = 's'
debug = false
lto = true
codegen-units = 1
panic = 'abort'
strip = true
incremental = false
