#!/usr/bin/bash

set -e

rm -rf build
mkdir build

cd frontend
trunk build --release
cd ../
cp -r frontend/dist build/
cp -r frontend/assets build/

cd backend
cargo build --release
cd ../
cp target/release/little-locator-backend build/

cp backend/config.json build/
cp python-requirements.txt build/

mkdir build/rhkc
cp backend/src/redhat_keycloak_auth/auth.py build/rhkc/
cp geckodriver build/

cd build
python3 -m venv ll_rhkc
source ll_rhkc/bin/activate
pip3 install -r python-requirements.txt
